config/routes.rb
FarmerTate::Application.routes.draw do

  root 'farm#index'

  get 'games/round-up' => 'games#round_up', as: :round_up_game
  get 'games/milk-cow' => 'games#milk_cow', as: :milk_cow_game
  get 'games/horse-ride' => 'games#horse_ride', as: :horse_ride_game
  get 'games/feed-animals' => 'games#feed_animals', as: :feed_animals_game
  get 'games/exercise-pigs' => 'games#exercise_pigs', as: :exercise_pigs_game
  get 'games/visit-vet' => 'games#vet', as: :vet_game

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/farm_controller.rb
class FarmController < ApplicationController

  def index
    # this is our starting page
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def round_up
    render text: "This will be the round up game"
  end

  def milk_cow
    render text: "This will be the cow milking game"
  end

  def horse_ride
    render text: "This will be the horse riding game"
  end

  def feed_animals
  end

  def exercise_pigs
    render text: "This will be the pig exercise riding game"
  end

  def vet
    render text: "This will be the place to visit the vet"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/farm_helper.rb
module FarmHelper
end

app/views/farm/index.html.erb
<div class="row">
  <h1 class="text-center">Welcome to Farmer Joe's Farm</h1>
</div>
<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <p class="big-text text-center">
      <%= image_tag 'farmer-1.jpg', class: 'pull-right' %>
      I am farmer Joe.  I lost my sheep.  My cows need milked. My animals are losing health.  Click on a picture below to help. Thanks,
    </p>
    <p class="big-text text-center">
       -- Farmer Joe
    </p>
  </div>
</div>
<div class="row">
  <div class="col-md-4 text-center">
    <h3>Round-Up Sheep</h3>
    <%= link_to((image_tag  'sheep-1.gif', height: 200), round_up_game_path) %>
  </div>
  <div class="col-md-4 text-center">
    <h3>Milk Cows</h3>
    <%= link_to((image_tag  'cow-1.png', height: 200), milk_cow_game_path) %>
  </div>
  <div class="col-md-4 text-center">
    <h3>Ride Horses</h3>
    <%= link_to((image_tag  'horse-1.jpg', height: 200), horse_ride_game_path) %>
  </div>
</div>
<div class="row">
  <div class="col-md-4 text-center">
    <h3>Feed Animals</h3>
    <%= link_to((image_tag  'hay-1.jpg', height: 200), feed_animals_game_path) %>
  </div>
  <div class="col-md-4 text-center">
    <h3>Exercise Pigs</h3>
    <%= link_to((image_tag  'pig-1.jpg', height: 200), exercise_pigs_game_path) %>
  </div>
  <div class="col-md-4 text-center">
    <h3>Visit Vet</h3>
    <%= link_to((image_tag  'red-cross.jpg', height: 150), vet_game_path) %>
  </div>
</div>

app/views/games/feed_animals.html.erb
<div class="row">
  <h1 class="text-center">Feed Farmer Joe's Animals</h1>
</div>
<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <p class="big-text text-center">
      <%= image_tag 'farmer-1.jpg', class: 'pull-right' %>
      My animals are hungry, can you help feed them?  Drag the hay with your mouse to each animal's mouth.  Watch out for wolves and snakes, we dont want to feed them!
    </p>
    <p class="big-text text-center">
       -- Farmer Joe
    </p>
  </div>
</div>
<div class="row">
  <div class="text-center">
  <canvas id="feed-animals-game"></canvas>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>FarmerTate</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>